### ISSUE TITLE
1.19 수정사항

### ISSUE THREAD

**Issue by chaerang2** [codestates/Todo.gg_Client#35]
### ISSUE
- Type: `bug`, `feature`

### TODO
- [x] 회원가입 시 모달창 닫기 
- [x] 기간 미정 시 9999.01.01로 보내기
- [x] 프로젝트 추가 시 일치하지 않는 유저입니다 메세지 안보이게 하기
