### ISSUE TITLE
1.20 수정사항

### ISSUE THREAD

**Issue by chaerang2** [codestates/Todo.gg_Client#46]
### ISSUE
- Type: `bug`, `feature`

### TODO
- [x] 프로젝트 멤버 프로필 노출 코드 수정
- [x] 프로젝트 멤버 중복 추가 방지
- [x] 프로젝트 삭제
- [x] 프로젝트 수정 권한관리
- [x] 투두리스트 완료날짜 분기
- [x] 로그인 시 리스트 즉시 노출 안되는 버그 해결
