### ISSUE TITLE
리스트 페이지-entry

### ISSUE THREAD

**Issue by h900506** [codestates/Todo.gg_Client#7]
### ISSUE
- Type: `bug`, `feature`

### TODO
- [x] 진행률에 따라 색으로 표시
- [x] 프로젝트 게시자 프로필사진 추가
- [x] 프로젝트 참여자 프로필사진 나열
- [x] 프로젝트 이름, 기간, [todo/in progress/done](킬뎃, %포함) 표시
