### ISSUE TITLE
css/edit 1.31

### ISSUE THREAD

**Issue by chaerang2** [codestates/Todo.gg_Client#79]
### ISSUE
- Type: `bug`, `feature`

### TODO
- [ ] 투두리스트 프로젝트 이름 가운데 정렬
- [ ] 투두리스트 버튼 마우스오버하면 커서 포인터 변경
- [ ] 투두리스트 프로젝트 이름 길면 말줄임표되게하기
- [ ] 태스크카드 인원 추가 버튼 중앙정렬
- [ ] 태스크카드 조회 div와 수정 div height 맞게 수정
- [ ] 종료날짜 미정 체크 시 날짜비활성화 ( 길이 바뀌지 않게하기위함)
