### ISSUE TITLE
네비바 기능구현

### ISSUE THREAD

**Issue by chaerang2** [codestates/Todo.gg_Client#8]
### ISSUE
- Type: `bug`, `feature`

### TODO
- [ ] 로고 클릭 시 메인페이지로 이동
- [ ] 로그인 상태라면 로그아웃 버튼 및 마이페이지 버튼 표출
- [ ] 로그아웃 상태라면 회원가입 버튼 및 로그인 버튼 표출
